apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
data:
  connection_string: mongodb://username:password@mongo-service:27017
  DatabaseName: CatalogDb
  CollectionName: Products
  BrandsCollection: Brands
  TypesCollection: Types